import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Providers from "@/components/Providers";
import Navbar from "@/components/navbar";
import 'react-toastify/dist/ReactToastify.css';
import { CounterProvider } from "@/components/CounterProvider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AskDocAi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <Providers>
        <CounterProvider>
          <html lang="en">
            <body className="min-h-screen font-sans dark bg-gradient-to-tr from-background to-slate-900">
              <Navbar />
              {children}
              <Toaster position="top-center"/>
            </body>
          </html>
        </CounterProvider>
      </Providers>
    </ClerkProvider>
  );
}
